### ISSUE TITLE
Cookies are used even when use is not allowed

### ISSUE THREAD

**Issue by flololan** [flololan/EFHA_Ergonomic_Criteria_Bastien_Scapin#32]
Clicking on decline will still save a cookie (the cookie that saves the information of showing the cookie-banner again or not)

Expected behavior: If the user clicks on decline on the cookie-banner, there should be no cookie. So that when you reload the page it should show again the cookie banner

**Comment by Lyokolux** [comment]
We use the localstorage to store the information that we won't display this banner again :D
